### ISSUE TITLE
additional bash scripts

### ISSUE THREAD

**Issue by brntbeer** [githubtraining/example-githubapiscripts#1]
There's a few items to add to this repo either by extracting from other repos, or reproducing entirely here.
## TODO
- [ ] https://github.com/mattcantstop/gitline
- [ ] https://github.com/nathos/ghinfo
- [ ] https://github.com/IQAndreas/github-issues-import
- [ ] https://github.com/WtfJoke/rtc2git

**Comment by brntbeer** [comment]
cc @matthewmccullough @mattcantstop @jordanmccullough @nathos @PatrickBM @crichID @loranallensmith @jaw6. 

If any of you have ideas on how to do this or preferences how some of those get over here let me know. Otherwise i'll come up with something!

**Comment by jordanmccullough** [comment]
Amazing timing, @brntbeer! This just came up in [conversation](https://github.com/github/services/pull/278#discussion_r26674631) regarding bash script examples we'd like to refer to during and after our Implementation engagements.

To ensure the community and GitHub customers benefit from a single location, we might want to get a final :+1: from the [github/platform-samples](https://github.com/github/platform-samples) curators and place the example scripts over there.

Thoughts?

**Comment by mattcantstop** [comment]
My preference is for our team to own the repository that we share with customers and the community at large. We can bring in resources from other places but I prefer we have our own repository.

**Comment by jaw6** [comment]
> If any of you have ideas on how to do this

It's kind of "stupid git tricks" (I had to confirm it would work, even) but... you could add those repos as remotes and just merge them in. (There'll be _lots_ of `readme` conflicts, I'm sure.) It's almost certainly going to be faster/better organized to copy individual files over, but I guess you'd lose the history.

I guess my question would be: do you intend this to be a collection of useful scripts or demo scripts? Like, "here are things you might want to try before writing your own" or "here are things you could read and get ideas for what's possible" ? 

I'm guessing it's more the first one...? I guess what I'm getting at is if the purpose is to be generally useful (like, _do_ something) then I'd just copy them over as-is; if the purpose is to be instructional (like, _look_ and then do something else) it might be more valuable to adapt those scripts to fit in with the others already in here? (Or, if showing a diversity of approaches is its own thing, maybe folders to group these into similar categories or something?)

I'm ... not sure if I'm actually helping?

**Comment by jordanmccullough** [comment]
Thanks everyone for the inputs and ideas. We're definitely all on the same page regarding a one-repo resource for ease of reference for ourselves as much as our customers. :sparkles:

I've [reached out](https://github.com/github/platform-samples/issues/37) to the Platform folks and have the conversation started for us to begin using `github/platform-examples`. This provides us with a place where engineering can help us curate and caretake focused examples.

**Comment by brntbeer** [comment]
> This just came up in conversation regarding bash script examples we'd like to refer to during and after our Implementation engagements.

Thanks @jordanmccullough ! This was actually why i made this in the first place =) I commented over on that thread too.

Glad to see these being in the community spot of platform-examples tho!

**Comment by jordanmccullough** [comment]
@brntbeer, Appreciate the response and opening this thread which coincided so well with [conversations](https://github.com/github/services/pull/278#discussion_r26676867).

@brntbeer, @mattcantstop, @jaw6, I'm thrilled the Implementations and Training teams continue to play a crucial role in enabling customers and provide a springboard for extending the platform.

Aligning this goal with the [established `platform-examples/` repository](https://github.com/github/platform-samples) and capitalizing on existing engineering resources garners all the more strength and support for our efforts. The Docs Team's [interest](https://github.com/github/platform-samples/issues/37#issuecomment-83654213) in aligning with API examples and Developer Guides is all the more exciting, too.

If there are any other details to sort out, decisions which examples to submit first, or more what best next-steps look like, the team is just an @github/services-implementationspecialists mention away.
